openapi: 3.0.2
info:
  title: Yet Another Vapor Blog
  description: API backbone for yavb
  version: 1.0.0
servers:
  - url: http://localhost:8082/api
    description: Vapor blog API
  - url: https://warthog-fitting-purely.ngrok-free.app/api
    description: Ngrok endpoint
    # Add a relative server URL to the OpenAPI document. This allows you to use the rendered documentation to make requests to the instance serving the OpenAPI document itself.
#  - url: /api
#    description: OpenAPI Description
tags:
  - name: Auth
    description: Authentication and Authorization
  - name: Post
    description: Posts management, creation, deletion and modification
  
paths:
  /post/create:
    post:
      tags:
        - Post
      description: Create a new post
      operationId: createPost
      requestBody:
        required: true
        description: Needed info for create the new post
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Post"
      responses:
        '201':
          description: A success response with no content
        '400':
          description: Failed response with a string value for the reason. This is due to given post data is invalid.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostEditError"
        '409':
          description: Failed response with a string value for the reason. This is due to given post data have been taken.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerConflictError"
  /auth/register:
    post:
      tags:
        - Auth
      description: Register an account
      operationId: register
      requestBody:
        required: true
        description: The needed info for set up the account.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterInput"
      responses:
        '201':
          description: A success response with no content.
        '400':
          description: Failed response with a string value for the reason. This is due to given registration data is invalid.
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/RegistrationError"
        '409':
          description: Failed response with a string value for the reason. This is due to given registration data have been taken.
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ServerConflictError"

components:
    schemas:
        Post:
            type: object
            properties:
              title:
                description: Title for the post
                type: string
                example: Hello World, This Is My First Post
              body:
                description: Body of the post
                type: string
                example: This could go very very very long...
              summary:
                description: Summary of the post
                type: string
                example: This is the excerpt of the post
              isDraft:
                description: A boolean value indicates whether the post is a draft, if yes, it won't be returned from public endpoint. Default to 'false'
                type: boolean
                example: false
        PostEditError:
          type: string
          enum:
            - Title Can not be empty
        ServerConflictError:
          type: string
          enum:
            - Username has been taken
            - Email has been taken
        RegistrationError:
            type: string
        RegisterInput:
            type: object
            properties:
              contactInfo:
                  description: An valid email address the account will be asscociated to.
                  type: string
                  example: abc@xxx.com
                  pattern: (^(\\+[1-9]+(-?[0-9]+))?[- ]?([0-9\\- ]+)[0-9]$|^(?:[a-zA-Z0-9!#$%\\&‘*+/=?\\^_`{|}~-]+(?:\\.[a-zA-Z0-9!#$%\\&'*+/=?\\^_`{|}~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])$)
              username:
                  description: Case sensitive, must be >= 4 characters
                  type: string
                  minLength: 4
                  example: sunny
              password1:
                  description: Case sensitive, must be >= 4 characters
                  type: string
                  example: three_strAws!
              password2:
                  description: Must be at least 4 characters, and exact the same value as password1
                  type: string
                  example: three_strAws!
            required:
              - contactInfo
              - username
              - password1
              - password2
