# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Yavb

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    # - name: Run tests
      # run: swift test -v
  # build-ubuntu:

  #   runs-on: ubuntu-22.04

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Build
  #     run: swift build -v
  #   # - name: Run tests
  #     # run: swift test -v

  # build-mac:

  #   runs-on: macos-13

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Build
  #     run: swift build -v
  #   # - name: Run tests
  #     # run: swift test -v
