# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Yavb

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest, macOS-latest]
          
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Swift on macOS
      if: contains(matrix.os, 'macOS')
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: 5.9.0
    
    - name: Build
      run: swift build -v
    # - name: Run tests
      # run: swift test -v
